### ISSUE TITLE
Key generation for #nostr

### ISSUE THREAD

**Issue by kfrancis** [zone117x/Secp256k1.Net#21]
Hey,

Trying to use your lib to create the key pair for use on nostr (see [NIP-01](https://github.com/nostr-protocol/nips/blob/master/01.md))

```c#
using var secp256k1 = new Secp256k1();

// Generate a random private key.
var privateKey = new byte[32];
using var rnd = RandomNumberGenerator.Create();
do { rnd.GetBytes(privateKey); }
while (!secp256k1.SecretKeyVerify(privateKey));

// Create a public key from the private key.
var publicKey = new byte[64];
if (secp256k1.PublicKeyCreate(publicKey, privateKey))
{
    // Serialize the public key
    Span<byte> serializedKey = new byte[Secp256k1.SERIALIZED_COMPRESSED_PUBKEY_LENGTH];
    if (secp256k1.PublicKeySerialize(serializedKey, publicKey, Flags.SECP256K1_EC_COMPRESSED))
    {
        var pubKeyHex = BitConverter.ToString(serializedKey.ToArray()).Replace("-", string.Empty).ToLowerInvariant();
        Key = pubKeyHex;
    }
}
```

But I'm getting values that are maybe slightly too long? I'm expecting a hex string 64 bytes/chars long but I'm getting 66 byte/chars long. I must be doing something wrong, but I can't tell what.

By the way, WIP .NET MAUI client is [here](https://github.com/kfrancis/NuSocial)

**Comment by zone117x** [comment]
Hello,
Compressed secp256k1 public keys are 33 bytes (66 hex chars) in length, because they include a prefix byte to indicate the Y coordinate, i.e `[Y coordinate (1 byte)] + [X (32 bytes)]`. Here's more info from the first google result: https://medium.com/asecuritysite-when-bob-met-alice/02-03-or-04-so-what-are-compressed-and-uncompressed-public-keys-6abcb57efeb6

The NIP-01 resource you linked is using [BIP-340 Schnorr Signatures for secp256k1](https://bips.xyz/340) which enforces compressed keys with an even-numbered Y value. This allows the prefix byte (`0x02` in this case) to be implicitly known, and thus isn't included -- resulting in a 32 byte pubkey.

It also states existing compressed keys can be used by simply dropping the prefix byte:
> it is also possible and safe to repurpose existing key generation algorithms for ECDSA in a compatible way. The secret keys constructed by such an algorithm can be used as sk directly. The public keys constructed by such an algorithm (assuming they use the 33-byte compressed encoding) need to be converted by dropping the first byte. Specifically, [BIP32](https://bips.xyz/32) and schemes built on top of it remain usable.

So it sounds like you need to modify your code to do something like:
```cs
var trimmed = serializedKey.Slice(1);
var pubKeyHex = BitConverter.ToString(trimmed.ToArray()).Replace("-", string.Empty).ToLowerInvariant();
```
